### ISSUE TITLE
[PSA] counter control plane API

### ISSUE THREAD

**Issue by hanw** [p4lang/p4-spec#309] opened 2017-06-25 23:51 UTC
The behavior of the control plane API calls should be documented.

What is the intended meaning of 'sync_read'?

What do control plane calls 'start' and 'stop' do?

**Comment by jafingerhut** [comment] 2017-07-01 22:31
@cc10512 Any thoughts on these questions, or a pointer to whoever wrote this part of the draft PSA document so we can ask them?

**Comment by cc10512** [comment] 2017-07-03 03:40
@jafingerhut, as you've surely noticed all the @ControlPlaneAPI calls (and the annotation) are within comments. The idea is that we have a one stop shop to understand how to program _and_ configure an extern and build toward a full specification that can be used by tools to generate all the necessary APIs.

A 'sync_read' is a read that forces the counter to accumulate all outstanding operations and then return a value. That is as opposed to a 'read' that reads whatever is there when the request hits. 'start' and 'stop' are intended to allow pausing and resuming counter operations.

I agree we should document these if we all agree that having the specification in the data plane is a good idea.

**Comment by jafingerhut** [comment] 2017-07-03 06:03
@cc10512 I see @controlplaneapi directives in the PSA.mdk source file, and I see those in the HTML output as well.  The function signatures alone are not sufficient documentation.  They need at least a few sentences of text for each one, describing the intended behavior.

I have read somewhere that it is in the charter of the P4 control plane work group to define the APIs for not only table add/delete operations, but also for externs in the PSA.  Should we be inviting at least one or two people from that group to the PSA meetings to help flesh these out?

**Comment by jafingerhut** [comment] 2017-07-03 06:04
Why would you want the control plane to call stop(), assuming that this means that data packets can continue to be forwarded, but counter updates will no longer be occurring?

**Comment by cc10512** [comment] 2017-07-03 06:34
One scenario: in an INT-dominated world, where we continuously collect information, we might get overwhelmed with counting everything, and we could rather sample at certain intervals.

Involving the API WG is a good idea, but note that we already have them involved. Samar, Waqar, and Tom work with Lorenzo at Google and are part of this crowd, and I know @antoninbas is keeping an eye on the discussions, and had several proposals on how to cleanup action selectors and cloning/recirc.

**Comment by cc10512** [comment] 2017-09-13 21:17
@jafingerhut, I believe P4Runtime has the control plane APIs for counters spec-ed out, and your examples are extensive for the data plane. Shall we close this issue?

**Comment by jafingerhut** [comment] 2017-11-03 19:48
Sorry I dropped the ball on this question.  I am closing this issue.

**Closed by jafingerhut** 2017-11-03 19:48 UTC
Labels: portable switch architecture
