### ISSUE TITLE
Question: P4 parsers and controls are fundamentally one packet in, one packet out constructs?

### ISSUE THREAD

**Issue by jfingerh** [p4lang/p4-spec#893] opened 2020-10-10 13:08 UTC
I believe I know the answer is "yes", but wanted to double check with other P4 language experts in case I was missing something.

Most P4 architectures for switches have capabilities for doing multicast, or cloning packets, such that for the architecture as a whole, a single packet in can result in multiple packets out.  All of those architectures perform such packet copying outside of parser and control blocks.

As far as I can tell, this is a fundamental property of P4 parsers and controls, i.e. given a single packet [1] that triggers the execution of a parser or control, it will run to completion and result in one set of headers and/or metadata out.  Those headers and/or metadata out can then be used by the architecture to cause duplication.

However, there is no way given the P4 language semantics we have today to define a control such that at some point you call a "make N copies of this packet" extern, and all of the code in the control from that point afterwards is executed once for each of those copies.

[1] More generally, an architecture could define that some kinds of events other than packets could trigger a control to execute, e.g. a timer firing in the device.

**Comment by vgurevich** [comment] 2020-10-11 00:14
I think that one-packet-in-one-packet-out semantics makes it infinitely easier to reason about the program behavior, otherwise how would you know which header/metadata refers to which packet. If you have a physical pipeline, where replication can happen in the middle, I'd expose it as two separate controls: one "pre-replication" one and another one "post-replication" one and this is what we do in ingress/egress pipelines on most switching devices anyway.

**Comment by jnfoster** [comment] 2020-10-12 14:02
Formally, the spec doesn't mandate one-packet-at-a-time.

You could imagine a vectorized parser that has multiple packet_in objects,
and populates multiple header and metadata values. Of course, it would be
clunky since P4 doesn't have iteration.

The Concurrency model talks about "threads." So if each packet is a
"thread" -- as on most targets I'm aware of -- then you can think about
things this way.

**Comment by mbudiu-vmw** [comment] 2020-10-12 17:07
I don't think there would be a problem to extend P4 to support a form of "multicast", (or flatmap from functional programming, similar to the "map" in map-reduce). The problem is that it is not clear how this can be efficiently compiled on some target architectures. On a target like Tofino multicast is more "configurable" than "programmable". For such a target, leaving multicast to the architecture is quite natural. For an open-flow-like target we could easily add support in the language, leaving the multi-threading aspects untouched.

**Comment by mbudiu-vmw** [comment] 2020-10-12 17:12
But, yes, in order to keep the threading model unchanged we probably would need to place multicast before the control that consumes the multicast packets, and have the control process each packet independently.

**Comment by jafingerhut** [comment] 2020-10-12 18:42
I am not currently advocating for a change like this to the P4_16 language, despite the fact that I've written so many words below in this comment. :-)  Consider it the childlike wonder of realizing that I learned a little about continuations years ago, and it seems like this is related.

However, I wanted to point out that _if_ one wanted to make such a change, one way that seems easiest to understand, and perhaps define and reason about, would be a new kind of extern function call that you would call once in the code, e.g

```
        if (do_multicast_replication) {
            // point A
            multicast_replication(/* in */ mcast_group_id, /* out */ egress_port, /* out */ replication_id);
            // point B
        }
```
From the point of execution in the control up to point A, a received packet P0 would have one 'thread', one copy of the packet in the device, one set of values for all header and metadata variables, etc.

The extern would "return N times instead of only once".  That is, starting at point B there would be a thread for packet P1, which was a copy identical to P0, except for the values of the out parameters egress_port and replication_id.  That thread would execute the rest of the control apply block from that point onwards, until it was done.

Independently, there would be another thread for packet P2, which was identical to P0 except for the values of egress_port and replication_id, and P2's thread would in general have _different_ values for those out parameters than P1's thread got.  P2's thread would also execute the rest of the control apply block from that point onwards, until it was done.

That is effectively what a separate ingress and egress control, with multicast replication between them, is doing, i.e. a single thread in ingress becomes multiple threads in egress.

Of course, this gets messier if you consider the possibility of calling an extern function like that multiple times in the same control ...  But this is exactly analogous to how it can get bewildering to mentally trace the packet flow of all packets through a switch ASIC when they can do multicast replication, then one or more of those copies recirculate, and each of them in turn may or may not perform multicast replication, independently of each other ...

I don't think this idea makes any sense whatsoever for a target device that implements multicast in a "PRE plus packet buffer plus traffic manager" hardware block, but it _might_ make sense for targets that can do multicast differently (e.g. general pupose CPUs).

**Comment by mbudiu-vmw** [comment] 2020-10-12 18:44
We already have a construct we can use for continuation: it's a control block.

**Comment by jfingerh** [comment] 2020-10-15 15:27
@mbudiu-vmw In what way is a control block able to implement a continuation, in the Scheme call-with-current-continuation sense?  I'm not asking for one, mind you -- my only point is that P4_14 and P4_16 do not have one.  Even extern functions and methods, as powerful as they can be, are limited to returning once per time they are called.  P4 controls can be called from other calls, but they are limited to returning once for each time they are called.

P4 allows duplication of packets/events to occur _between_ parsers and control, if the architecture defines that to occur, but only between them, not within them.

**Comment by jnfoster** [comment] 2020-10-15 15:44
I don't think we need anything as powerful as `call/cc`. We just need a way to represent the "rest of the program" for a given set of generated packet. I think @mbudiu-vmw's point was that a `control`, presumably instantiated for each new packet, seems like one way to achieve that.

**Comment by jnfoster** [comment] 2020-10-15 15:48
Well, externs and architectures can do anything...

**Comment by mbudiu-vmw** [comment] 2020-10-15 15:49
The invocation is dynamic. In your example the code is also statically created.

**Comment by jfingerh** [comment] 2020-10-15 15:59
@mbudiu-vmw Sorry, in my example _what_ code is statically created?  Are you thinking of some kind of compilation technique that takes my example code in this comment https://github.com/p4lang/p4-spec/issues/893#issuecomment-707284742  and mechanically transforms it into two or more control blocks, one control containing the code before the `multicast_replication()` extern function call, and the other control containing the code after the `multicast_replication()` call?

**Comment by mbudiu-vmw** [comment] 2020-10-15 18:05
We could write some code to do the transformation you suggested, but it probably would not be portable. In many pipelines multicast is not very flexible; for example, it may occur in a fixed point (e.g., between ingress and egress), and it can be done exactly once for each packet (you cannot multicast the result of the multicast). So to automatically map such a code to an architecture with constraints you will have to do some complex analysis. E.g., what if some operations invoked after multicast are not supported in egress? 

Also, your code example above looks more like 'fork' than call with a continuation. 

As far as I know, open-flow has a multicast operation, how did they solve this problem? My guess is that it has to be used in a very stylized way for the targets to support it. I proposed a 'flatmap' when I was at Barefoot about 6 years ago, but that proposal was never seriously considered. 

This sounds like a good subject to discuss in the design meetings. For me personally the main unknown is the constraints imposed by concrete target architectures.

**Comment by jafingerhut** [comment] 2020-10-15 18:20
Thanks for the notes.

Again, given the number of comments I've made here, I want to stress that the original purpose of this question is to confirm my belief that P4 parsers and controls cannot behave like this, according to the current P4_16 language specification.  I don't currently have a goal to add such a feature to the language.

Nate, regarding your comment about externs and architectures can do anything, the current language spec says that in order to write a correct P4_16 compiler, externs can neither read, nor modify, and variables in the calling P4 parser or control, unless they are explicit parameters, and in that case the extern's access is restricted by the direction in/out/inout.

It seems difficult for me to imagine how one could attempt to say "here is my architecture with this new multicast extern, and it has the effect of causing all parts of a P4 control that call it, from the point of the extern call afterward, to execute N times, but the part before that extern call are only executed once".  And have that be consistent with the current P4_16 language spec.  Everything I can think of that describes parser and control execution is that you start at the beginning, and continue to the end (with early exit possible only via transition to accept or reject in a parser, or 'exit' statement in a control, and no other way), and end with a result that is consistent with sequential execution.

I can imagine defining an architecture and extern(s) such that invoking an extern will later cause N packets to begin execution in some parser or control.  But they wouldn't be allowed to jump to the middle of the execution flow -- they would have to start at the beginning.

**Comment by jnfoster** [comment] 2020-10-15 18:22
I was thinking that the extern could create "threads" for each generated
packet, each running the code in a specified control. We would need to
tweak the language a tiny bit to allow specifying which control, but I
don't think it's a dramatic change... the PRE on PSA already does this,
just implicitly.

-N

**Comment by mbudiu-vmw** [comment] 2020-10-15 18:23
Right, I think both and Nate's point is that by using a control as a continuation, which executes from the beginning, you can obtain the desired behavior. Which is really how v1model works today.

**Comment by jnfoster** [comment] 2023-11-11 13:12
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.

**Closed by jnfoster** 2023-11-11 13:12 UTC
Labels: question
