### ISSUE TITLE
Add support for key=value pairs in annotations

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4-spec#605] opened 2018-03-27 15:30 UTC
This would enable annotations like
```
@pkginfo(name="my package", date="2018/3/29", version=2)
```

**Comment by ChrisDodd** [comment] 2018-03-27 16:45
duplicate of #99 ?

**Comment by mbudiu-vmw** [comment] 2018-03-27 16:48
Seems to be. But the key=value part does not seem to be implemented...
So we should probably reopen that.

**Comment by ChrisDodd** [comment] 2018-03-27 16:51
IIRC at the time it was decided that full java-style <identifier> = <expression> annotations were not needed.  But they should be relatively easy to add; the main concern is not impacting existing uses of simple <expression> annotations.

**Closed** 2018-06-13 00:47 UTC
Labels: Fixed
