### ISSUE TITLE
simple_switch: Conditional execution in actions is not supported 

### ISSUE THREAD

**Issue by krupal-raiyani** [p4lang/p4-spec#716] opened 2019-01-05 14:04 UTC
I am new to P4 and just came across below error while doing setValid() in if block of action .Am I doing something wrong which is not yet supported by simple_switch or v1model?

-Error Block----------
> p4c-bm2-ss --p4v 16 "pTest.p4" -o "pTest.json"
pTest.p4(21): error: MethodCallStatement: Conditional execution in actions is not supported on this target
   hdr.vlans.setValid();
   ^^^^^^^^^^^^^^^^^^^^
```
#include <core.p4>
#include <v1model.p4>

#include "header.p4"
#include "parser.p4"

typedef bit<9> egressSpec_t;

control ingress(inout headers hdr, inout metadata meta, inout standard_metadata_t standard_metadata) {
    action _drop() {
        mark_to_drop();
    }
    action add_ppp_fwd(bit<16> sessionID, bit<48> dstAddr, bit<48> srcAddr, egressSpec_t port, bool pushvlans, bool pushvlanc, bit<16> vlans, bit<16> vlanc) {
        if(pushvlans && pushvlanc){
            hdr.ethernet.etherType = 16w0x8100;
            hdr.vlans.setValid();
            hdr.vlans.vlanID = vlans;

```

**Comment by krupal-raiyani** [comment] 2019-01-05 14:19
Ops I guess I just created issue at wrong place and not able to delete the issue.

**Comment by antoninbas** [comment] 2019-01-05 19:54
Duplicate of https://github.com/p4lang/p4c/issues/1515

**Closed by antoninbas** 2019-01-05 19:54 UTC
