### ISSUE TITLE
P4_16: Allow headers to contain 'bit-vector structs'

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#342] opened 2017-07-02 18:00 UTC
Feel free to mark this issue "Post P4_16" if it helps.  I just want to get the issue out there right now.

Define a 'bit-vector struct' to be one that contains only these kinds of fields:
+ fields of type `bit<W>` or `int<W>`
+ fields of a struct type that is also a 'bit-vector struct'

Such a 'bit-vector struct' has a straightforward way to define how extract() and emit() methods would work on them, by following the order that fields are defined in the struct.

The proposal is to extend 'header' types to allow them to have 'bit-vector struct' types as members.

Motivation: This can be a programmer convenience to group multiple consecutive related header fields together, passing them as arguments as a unit, making them control plane action parameters as a unit rather than as individual fields, etc.  It does not provide any additional _capability_ over what can do with the P4_16 v1.0.0 language -- just a shorter way to express it in some cases.

There is no need to introduce any new keyword or syntax for what I call 'bit-vector struct' here, and there may be a better name for that concept.  The compiler would simply check that a struct that one tried to make a member of a header was a bit-vector struct, or not, and give an error if it was not.

**Comment by jnfoster** [comment] 2017-08-15 02:31
Super nice!

Any volunteers to prototype it as an extension in the p4c front-end?

**Comment by familysingh** [comment] 2017-10-06 16:09
Andy, 
I use familysingh with github,  but my work email is hemant@mnkcg.com.  This issue came to my attention yesterday.  The problem is a show stopper because there will always be a need to save instructions in switching ASIC or some switch code may not compile.  Using a bit-vector struct in P4 header saves instructions.  **The frontend code change for this issue is straightforward**.   However, even if we fix this issue, P4 code won't compile in certain common situations unless Issue# 383 is also resolved.  Switching code can use a search key which comprises only of bit fields.  One has to assign a header's struct fields to the search key.  For example the search key uses 32 bits for dst ip.  But the struct has lower28 and upper4 bits.  We are back to square one.  

Hemant
http://mnkcg.com

**Comment by hesingh** [comment] 2019-01-08 13:13
Here is a note for specific changes to the P4-16, version 1.1.0 specification.

In section 7.2.7, the table incorporates the following change.
Change value at the intersection of header column and struct row to “allowed” with an asterisk.  The asterisk is a foot note saying the struct must only contain bit-fields, integers, Serializable Enum, and Boolean.  Note, this table does not allow Boolean in a header.  However a struct with the Boolean is allowed.  What if such a struct is included in the header?  Emit can serialize the Boolean in the struct, so why not allow the Boolean in the struct?

**Comment by mbudiu-vmw** [comment] 2019-01-08 16:17
You should supply a PR against the spec.

**Comment by hesingh** [comment] 2019-01-08 21:11
Ok.  I have created a repo of the P4 spec.  I am wading thru the repo to see where to make the change and then submit a PR.

**Comment by jafingerhut** [comment] 2019-01-08 21:31
The only file that one typically needs to change, for changes to the P4_16 language spec, is this one:

p4-16/spec/P4-16-spec.mdk

**Comment by jafingerhut** [comment] 2019-01-08 21:34
If you want to run the Madoko program and LaTeX to generate the updated HTML and PDF output, for your own double-checking, see the README.md in that same directory, and/or run the setup-for-ubuntu-linux.sh script on an Ubuntu Linux 16.04 or 18.04 system to install the necessary software, then run 'make'.

**Comment by hesingh** [comment] 2019-01-08 21:36
Thanks, Andy!

**Comment by hesingh** [comment] 2019-01-10 16:20
There is minor pending work now that the nested structs code is checked into the p4c repo.  The pending work investigates adding int<W>, SerEnum, and boolean to supported types inside a struct.  On more thought, the boolean cannot be added to the struct if the struct is inside a P4 header.  The reason is, once the flattenHeader pass flattens the struct, the boolean ends up in the header.  A P4 header cannot include a boolean.  My vote is to not include boolean with nested struct support.

**Comment by mbudiu-vmw** [comment] 2019-01-10 16:36
You can file a new issue to allow booleans in headers.

**Comment by hesingh** [comment] 2019-01-10 16:44
ok, thanks.

**Comment by hesingh** [comment] 2019-01-10 16:49
Filed new issue.

https://github.com/p4lang/p4c/issues/1653

**Comment by hesingh** [comment] 2019-04-16 20:01
Even this issue should be closed, when or before, the P4-16 spec has been updated for nested bit-vector struct support.

**Comment by mbudiu-vmw** [comment] 2019-04-22 17:32
This is addressed by #719

**Closed by mbudiu-vmw** 2019-04-22 17:32 UTC
