### ISSUE TITLE
[PSA] Multiple clones

### ISSUE THREAD

**Issue by samar-abdi** [p4lang/p4-spec#614] opened 2018-04-29 21:31 UTC
The cloning ability in PSA seems to be restricted to only one clone (we have a bool in ingress_output metadata to indicate if packet should be cloned, and a single param for clone session ID).

What if we wanted to create N (>1) clones to different ports, and carrying different metadata?

Related, in v1model, does the clone3 extern call create a new clone every time it is called, let's say in multiple table actions? Thanks!

**Comment by jafingerhut** [comment] 2018-04-29 21:56
I do not know the v1model clone3 extern call details well enough to answer that part of your question, but I would be quite surprised if it was designed to enable making multiple clones of a packet during a single 'pass' of ingress or egress control block processing.  It is probably intended to be restricted to at most one clone for each ingress or egress control block execution.

For PSA, would using multicast in the PRE to create N (> 1) copies of the packet, differing only in their 'instance' metadata field, suit your purposes?  If the metadata you wanted different in each copy was small enough to make it practical, you could include the union of that metadata with the packet, and later packet processing code could use only the subset you cared about for that copy.

Alternately, if it was reasonable to have later tables that contained the unique-per-copy data that you wanted, you could avoid carrying such data with the pre-multicast-replicated packet, and look it up while processing each copy.

**Comment by samar-abdi** [comment] 2018-04-29 23:48
Thanks Andy. For different metadata, either approach you mentioned is good. The problem is that multicast ends up "losing" the original packet. The intent is to let the original packet go as destined by the ingress pipeline, and have it's clones go to known egress ports (perhaps with some header modification). So, really a CloneGroup equivalent of MulticastGroup would have been ideal.

**Comment by jafingerhut** [comment] 2018-04-30 00:46
If you want to try to get a solution based on what PSA defines and nothing else, another possibility is to clone 1 packet on ingress the first time the packet is processed, and also resubmit the packet back to ingress, where it is cloned again, with different destination/clone-session and metadata the second time around.  By resubmitting N times, you can get N+1 different clones with their own independent metadata, but all with the original input packet received from the input port.

It does use up more ingress processing bandwidth that might otherwise be used for processing new packets by resubmitting so many times, of course.

**Comment by samar-abdi** [comment] 2018-04-30 01:11
Thanks Andy. This is a very cool idea and I had considered it earlier, but it will require a counter and such a program might be very tricky to compile to a device that supports such feature natively.

Bandwidth is not a huge issue since the number of such packets will be a very very small fraction of the overall traffic.

Perhaps, we can consider CloneGroup for PSA 1.X, and it can clearly be implemented under the hood using recirculation?

**Comment by jafingerhut** [comment] 2018-04-30 01:11
OK, honestly I will stop suggesting other variations very soon, probably with this comment :-)

First time packet is processed on ingress, forward the original packet as 'normal', and also make a single clone to the PSA_PORT_RECIRCULATE port, which the PSA spec says should be supported (I brought up this case in a PSA work group meeting specifically to check with people whether they thought it should be supported, and I recall at least one person saying yes, with no dissenters, but I guess it really remains to be seen whether implementers truly support that case).

The clone will go through egress processing (which could be minimal based upon identifying it is a clone, and whatever metadata you add to the packet), recirculate back to ingress, where _that_ time it could use multicast to send as many copies as you want to different places, independent of where the original non-cloned packet went.

**Comment by samar-abdi** [comment] 2018-04-30 03:40
Andy, your suggestions are always brilliant and very welcome, so please don't feel inhibited in any way :)

My current struggle with this problem is having to balance the portability of the P4 program with the simplicity of the P4 compiler for each target device. There are multiple ways of expressing this behavior in P4, as you mentioned, but the compiler will inevitably require annotations as guidance to map such a program to a given fixed function architecture. I would like to avoid custom annotations as much as possible.

A clone group makes the program semantics much more obvious, and can be implemented in the two ways you mentioned, or through a fixed function block without recirculation if the target supports it.

**Comment by jafingerhut** [comment] 2018-10-23 20:06
Changes to this are in progress that should be part of PSA version 1.1, hopefully to be released November 2018.  https://github.com/p4lang/p4-spec/pull/665

**Comment by hanw** [comment] 2018-10-24 20:51
Resolved with #665

**Closed by hanw** 2018-10-24 20:51 UTC
