### ISSUE TITLE
Direct and indirect actions in a single table entry

### ISSUE THREAD

**Issue by samar-abdi** [p4lang/p4-spec#647] opened 2018-06-12 22:00 UTC
@jafingerhut @antoninbas @vgurevich 

PSA today allows tables to be either direct (the action is specified in flow) or indirect (the table action is a pointer to an action in a different table) using the action profile implementation attribute.

We have found several use cases, where the controller would greatly benefit by allowing both direct and indirect actions in a single table entry. Of course, this can be easily implemented by having two tables with identical match keys: one with direct action, and another with an action profile implementation. 

However, the controller SW can benefit by combining such tables because it would not have to deal with having to duplicate match keys in two tables, and having to co-ordinate the order of programming of the two table entries etc. I am also aware of fixed function targets that support this combined direct and group action natively. On such targets, the switch SW will benefit by not having to do a similar co-ordination between the two P4 tables.

So, the proposal is to allow something like this:

ActionProfile(...) ap;

table t {
  key = {...}
  actions = { a, b, c}  // these are the direct actions
  indirect_actions = { x, y, z} // these are the indirect actions implemented by `ap`
  implementation = ap;  // action profile instance that implements x, y, and z
}

There are 3 types of entries that can be programmed to the table `t` and action profile `ap`

1. t: {match, a | b | c } - direct entry (no reference to entry in ap)
2. t: {match, member_id}; ap: {member_id, x | y | z} - indirect entry
3. t: {match, a | b | c , member_id}; ap: {member_id, x | y | z} - entry with combined direct and indirect action

There will also be some changes to P4Info and P4Runtime to accommodate this table, specifically to support case (3) above, but we can get to those if we first have the right support in PSA.

**Comment by mbudiu-vmw** [comment] 2018-06-12 22:20
We already have annotations for actions `@tableOnly` and `@defaultOnly`. We can add annotations for `@indirect` anb `@direct`. That would not require changing the language.

**Comment by konne-google** [comment] 2018-07-27 23:52
Instead of making the semantics of action selectors even more complex by adding annotations, I think we can achieve the same effect by removing the indirection (between matches and groups, and between groups and members) from action selectors. Here's the trick:

We can have both direct and indirect actions if we add another table before the action selector, which performs a direct action and sets a group id. Something like this:

table match_table {
  key = {
    dst_ip_addr : ternary;
  }
  actions = {
    set_group_id_and_direct_action;
  }
}

action set_group_id_and_direct_action(group_id, param) {
  group_id = group_id;
  direct_action(param);
}

table selector_table {
  key = {
    group_id : exact;
    five_tuple : selector;
  }
  actions = {
    set_nexthop;
  }
  implementation = selector;
}

The problem is that the controller now has to program an unnecessary table in the action selector which just maps group ids to group ids. We can get rid of that problem by removing the indirection from the action selector semantics (there's no need to change any syntax), so that the controller has to just program one table instead of three for a given action selector.

If a user wants the indirection, they can add it back themselves using plain old P4 tables, similar to the match_table above.

Here's a doc that provides more detail:
https://docs.google.com/document/d/16S90w2-5SkuQ-uBtmM2T7Ix1xaHAsnWAb89AL3CixTI/edit#

**Comment by konne-google** [comment] 2018-07-30 21:43
I've made a copy of the detailed design doc that is available for everyone with the link:
https://docs.google.com/document/d/1vzJEDdzbBulwPU4Nh7OffjZpm4eYgmyhVqEmOHiMt6I

**Comment by konne-google** [comment] 2018-08-01 19:59
I've also created some slides:
https://docs.google.com/presentation/d/1Qi-v-TngxIfh5o-3hGQvYmVkZ5nlP9ghkchAbg1Bga0/edit?usp=sharing

**Comment by jafingerhut** [comment] 2018-09-24 06:46
@konne-google Has this issue been addressed by the addition of the one shot selector to the P4Runtime API?  If so, is it reasonable to close it as resolved?

**Comment by mbudiu-vmw** [comment] 2020-02-03 17:37
Can we close this?

**Comment by jnfoster** [comment] 2023-08-28 12:35
This seems safe to close...

**Closed by jnfoster** 2023-08-28 12:35 UTC
