### ISSUE TITLE
Should order of evaluation of assignment statements be mentioned in spec?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#867] opened 2020-06-04 19:10 UTC
Continuing down the trail of being nit-picky about weird statements/expressions where evaluation order might be significant.  I suspect most things are already fully specified here, but this seems to be a corner where it may not be yet.

Section 8.1 "Expression evaluation order" defines the order of evaluation of compound expressions.

While assignment statements are expressions in some languages (e.g. C), they are not expressions in P4_16, I believe.  Correction welcome there if I somehow got the wrong idea there.

If they are not expressions, then it seems that perhaps there might not be a mention in the spec today of the order of evaluation in an assignment statement.  Evaluating subexpressions in the left hand side before the expression on the right hand side seems to be a logical extension of the exiting left-to-right evaluation order rules already documented, which is not usually important, but would matter for examples like these:
```
// imagine a case where f has out or inout parameters,
// so whether f or g is called first is significant
hdr.my_hdr_stack[f(a,b)].f1 = g(a, b);

// if t1 has an action that calls exit, then whether g is ever called,
// and whether the assignment is ever done, depends upon the
// result of t1.apply(), if left-to-right evaluation is the preferred
// way to define evaluation order in assignments
hdr.my_hdr_stack[t1.apply().hit ? 1 : 2] = g(a, b);
```

**Comment by jnfoster** [comment] 2020-06-04 19:23
Maybe? I could also see the wisdom in leaving this unspecified... if the programmer meant for the effects to take place in a certain order they could use proper statements.

**Comment by jafingerhut** [comment] 2020-06-05 21:25
I am not pushing one way or the other here.  If it is unspecified evaluation order for this case, it will be an island of unspecified evaluation order in a sea of left-to-right evaluation order, so would be nice to explicitly say so.  I would think anyone reading the spec with "best guess from the context" thinking mode on would assume left to right for assignment statements, too.

**Comment by jafingerhut** [comment] 2020-06-05 21:32
I would bet good money that there are very few existing lines of P4 code whose behavior relies upon these order of evaluation rules, and such things are confusing to human readers, who are at least 50% of the audience for code (if not a larger fraction of the time) versus compilers.

If a linter or P4 compiler issues a warning every time the order of evaluation within a single expression or assignment might make a difference because of such side effects, I'd guess that 99% of the programs that caused such warnings to be issued would be test programs designed to trigger those warning messages.  The other 1% would be written by P4 developers who would see the warning, and either say "that's a bug", or "that is unclear code that I would prefer to split across two statements/expressions to make the order of evaluation explicit even to human developers that do not memorize the order of evaluation rules, because everyone knows that separate statements/expressions are evaluated sequentially".

**Comment by jnfoster** [comment] 2020-06-06 02:36
Totally. I'm not arguing against specifying evaluation order either. It might help us longer term to try to come up with a "philosophy" about this issue so we don't have to deal with each design decision in each new context.

**Comment by jafingerhut** [comment] 2020-06-06 08:20
I am aware of these two existing philosophies on evaluation order:

(a) Leave the P4 compiler developer the choice of evaluation order, which can differ from one P4 compiler to the next.  This gives maximum flexibility for generating efficient code for the target to the compiler, but for the P4 program writer, it gives non-portable behavior, if they ever write code that steps into the 'implementation defined order' expressions, whether they are aware they are doing so or not.  To me, this seems to be the "P4 developer is given a mine field and asked to walk across it.  Fortunately the land mines are far and few between."

(b) Define all legal statements and expressions in the language to have exactly one correct result.  In the common case where evaluation order does affect the result, the compiler writer is not hindered by this.  If a P4 developer does write expressions or statements that have data dependencies such that the result can differ among different evaluation orders, this does restrict the choices of the compiler to follow the language spec.

So far, it seems that P4_16 has gone the way of (b).  I think there are other languages that have used (a), but I don't have any particular ones in mind that I know have done so.

I'd like to offer a third possibility, that seems to me worth considering, both from a compiler implementer's perspective, and a "make the job of a P4 developer easier when reading and understanding code" perspective.

(c) Make the language specification explicitly say that if an expression or statement would ever give different results if the evaluation order among sub-expressions, parameters to function/method calls, etc. were different, then that expression/statement is not a legal one of the language.  That is, the compiler must detect this and give an error message.  In such a language, the compiler writer can know that for error-free programs, they can evaluate subexpressions, multiple parameters to function/method calls, etc. in any order they wish, because the behavior will be the same for any such order of evaluation.  P4 developers can feel confident knowing that programs that pass the compiler have no data dependencies hidden within single expressions, which most P4 developers would probably consider too unclear, anyway.  In those (I expect rare) instances where the compiler gives such an error, the developer simply breaks the expression/statement into two or more separate expressions/statements, with the order of evaluation made explicit and clear by normal sequential order of evaluation rules that everyone understands.

**Comment by jafingerhut** [comment] 2020-12-22 18:16
Apologies if you consider this noise, but pinging the following folks that I suspect may be interested in the contents of the Google doc linked below:
@mbudiu-vmw @jnfoster @ChrisDodd @liujed-intel @fruffy

Here is a couple-page Google doc I wrote on 3 alternative approaches the P4_16 language specification might take regarding expressions and/or statements whose behavior depends upon the order of evaluation of sub-expressions/statements.  Comments/questions/corrections all welcome (you are welcome to add comments in the doc, or to add notes in-line, preferably marked with your name)

https://docs.google.com/document/d/1aU9KKNXu_UVAG4uIxnm4gG0wgJ_YmOUJgrAAvxi-xpA/edit?usp=sharing

**Comment by jafingerhut** [comment] 2020-12-22 18:28
@milicaperic Pinging you for your attention to the previous comment, since you have worked on p4c issues regarding order-dependent constructs, too.

**Comment by mbudiu-vmw** [comment] 2020-12-22 18:55
@jafingerhut Currently we have chosen case 1. 
We can do a hybrid between 1 and 3 by giving warnings for such constructs, and the user can turn warnings into errors.
We do give warnings for some particularly egregious cases, like having aliased expressions passed to two out arguments in the same call.
This is also a burden for people who write verification tools, since they have to express the semantics correctly, and it is very tricky to do so. Looks like Gauntlet at least was wrong, since it didn't catch a bug.

**Comment by jafingerhut** [comment] 2020-12-22 19:01
@mbudiu-vmw Agreed we could do a hybrid between Approach #1 and #3 in that document, as long as we realize that such a hybrid has pretty much all of the disadvantages of Approach #1.

**Comment by mbudiu-vmw** [comment] 2020-12-22 21:02
I know that @ChrisDodd favors 2, and it has some advantages, but I don't think that this issue is so important as to require us to break compatibility with old programs. Ideally we solve it once and for all in one compiler pass and no user has to worry about it.

**Comment by jafingerhut** [comment] 2020-12-22 21:43
Both approach #2 and approach #3 are not backwards-compatible, but in slightly different ways.  Both have the same mitigating approach -- give warnings and/or errors from the compiler for all order-dependent constructs, so the P4 developer can change the code to make them order-independent.  Except for the few cases mentioned in the doc that are widespread (short-circuiting or/and, ternary operator, and switch statement), I doubt there are many order-dependent constructs in common use.

**Comment by fruffy** [comment] 2020-12-23 09:59
@mbudiu-vmw What is the bug that Gauntlet did not catch? I would like to look into this. I checked https://github.com/p4lang/p4c/pull/2640 but that issue was not caught because the particular program is not part of the test suite. 

From the perspective of developing verification tools, side effects have indeed been time-consuming. I had to write lots of custom tests in addition to the tests provided by p4c. The copy-in/copy-out semantics are also subtle in the sense that they are intermixed with scoping (e.g., actions inside a control can access all variables declared in that control). However, these difficulties largely came up because I was developing in tandem with fuzz testing, which generated outlandish programs. For many of the programs with problematic side effects I actually struggled to justify why anyone would write code this way. On the other hand, if P4 code is generated from synthesis tools or high-level compilers, which seems increasingly likely, these code combinations may not be that outlandish any more. Option 3 would unnecessarily restrict these tools in their expressiveness. 

I think the choice of warnings is the most sensible. It does not rock the boat too much but still gives developers a heads up that their code might lead to unexpected behavior. Although, going forward, exercising option 3 seems reasonable to me. It might be worth constraining new language constructs if they otherwise burdened side effect analysis. For example, slices already only allow compile-time known values. If the need arises to relax these constraints, it can still be done without breaking backwards compatibility? 

Option 3 makes developing tools that generate random code harder because you have to implement many special cases. However, these are not so different from the analysis the compiler does to warn about a particular code construct.

**Comment by mbudiu-vmw** [comment] 2020-12-23 19:15
I think that the output we were producing for the side-effects.p4 code was actually incorrect.
Perhaps you should contribute all these cases you wrote as tests to prevent further regressions.

**Comment by jnfoster** [comment] 2023-11-11 12:56
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.

**Closed by jnfoster** 2023-11-11 12:56 UTC
Labels: question
