### ISSUE TITLE
PSA: create examples to demonstrate the use of each `error` type

### ISSUE THREAD

**Issue by hanw** [p4lang/p4-spec#535] opened 2017-12-20 19:13 UTC
I don't know if we have ever had such example for v1model, but we should have them for PSA.

**Comment by jafingerhut** [comment] 2017-12-21 23:59
@vgurevich I have been hacking on an example program that sends packets that experience parser errors to the control plane, with a small 'to-CPU' header giving the parser error code and a few other fields that a control plane might want to know about the bad packet.

When you mentioned the idea of a P4 implementation that when experiencing an error during parsing, left the headers in an unknown/undefined state, do you mean a state where:

(a) emit'ing the headers in a reasonable order would still be guaranteed to reproduce the original input packet?

(b) Or do you mean that the resulting state might be one where emit'ing the headers would _not_ be guaranteed to reproduce the original packet?

If you mean (b), then we are OK to send the original packet as received by the ingress parser to the control plane, because ingress-to-egress clone is specified by PSA to send the original packet, before parsing began.  However, we would have no way defined in PSA to send the pre-parsed packet contents if a parser error occurred in the _egress_ parser, because egress-to-ingress clones are currently defined in PSA such that the cloned packet contents come out of the egress deparser.

If you don't mind such an implementation having no way to recover the original pre-egress-parser packet when the egress parser encounters a parse error, then no worries.

**Comment by jafingerhut** [comment] 2017-12-22 06:14
Created this PR with a proposed example program that demonstrates how to send a copy of packets that experience parsing errors to the control plane with a header containing info about where the packet came from, and what went wrong.  I can't think of much reason to do different things for different errors, except perhaps some should be copied to the control plane, where perhaps for other types of errors it might be preferable not to send a copy to the control plane, but simply count them.  https://github.com/p4lang/p4-spec/pull/541

**Comment by cc10512** [comment] 2018-01-14 01:54
Fixed by #541

**Closed by cc10512** 2018-01-14 01:54 UTC
